In [3]:
import numpy as np
 #generate a dummy data set

x = np.random.randint(10,50,100).reshape(20,5)
print(x.shape)
print(x)
#mean centring the data

x_mean = x-np.mean(x,axis=0)
print(x_mean)

(20, 5)
[[17 21 48 23 22]
 [46 39 47 13 33]
 [12 48 11 13 28]
 [37 26 35 45 40]
 [10 45 30 31 30]
 [24 45 18 40 39]
 [39 46 22 42 48]
 [42 49 39 19 27]
 [46 29 35 47 33]
 [27 44 39 20 39]
 [28 14 48 23 10]
 [45 13 33 43 35]
 [27 49 13 13 33]
 [10 31 37 40 33]
 [40 22 43 17 46]
 [33 30 43 35 20]
 [36 10 18 37 15]
 [41 26 11 31 40]
 [42 11 30 44 45]
 [28 46 14 42 22]]
[[-14.5 -11.2  17.3  -7.9  -9.9]
 [ 14.5   6.8  16.3 -17.9   1.1]
 [-19.5  15.8 -19.7 -17.9  -3.9]
 [  5.5  -6.2   4.3  14.1   8.1]
 [-21.5  12.8  -0.7   0.1  -1.9]
 [ -7.5  12.8 -12.7   9.1   7.1]
 [  7.5  13.8  -8.7  11.1  16.1]
 [ 10.5  16.8   8.3 -11.9  -4.9]
 [ 14.5  -3.2   4.3  16.1   1.1]
 [ -4.5  11.8   8.3 -10.9   7.1]
 [ -3.5 -18.2  17.3  -7.9 -21.9]
 [ 13.5 -19.2   2.3  12.1   3.1]
 [ -4.5  16.8 -17.7 -17.9   1.1]
 [-21.5  -1.2   6.3   9.1   1.1]
 [  8.5 -10.2  12.3 -13.9  14.1]
 [  1.5  -2.2  12.3   4.1 -11.9]
 [  4.5 -22.2 -12.7   6.1 -16.9]
 [  9.5  -6.2 -19.7   0.1   8.1]
 [ 10.5 -21.2  -0.7  13.1  13.1]
 [ -

In [4]:
#calculate the co varinace matrix of the mean centered data

cov_mat = np.cov(x_mean, rowvar=False)
print(cov_mat)

[[143.73684211 -54.57894737  20.78947368  28.57894737  36.10526316]
 [-54.57894737 193.32631579 -58.77894737 -54.76842105  23.28421053]
 [ 20.78947368 -58.77894737 166.01052632 -25.08421053 -20.71578947]
 [ 28.57894737 -54.76842105 -25.08421053 146.41052632  21.04210526]
 [ 36.10526316  23.28421053 -20.71578947  21.04210526 106.41052632]]


In [5]:
#calculating Eigen value and vectors 

eigen_value , eigen_vector = np.linalg.eigh(cov_mat)
print(eigen_value,eigen_vector)

[ 57.71473105  83.44288927 137.6545031  197.51579825 279.56681518] [[ 0.43059001 -0.41129707  0.62337197  0.27870518 -0.42327034]
 [ 0.49262185  0.28839279  0.33432095  0.05282293  0.74805919]
 [ 0.14395734  0.56556942  0.29196731 -0.64492624 -0.3977848 ]
 [ 0.36017485  0.53901049 -0.37110496  0.58262088 -0.32027454]
 [-0.64920438  0.37049053  0.52599724  0.40516196  0.02100332]]


In [6]:
#sort the eigen value in desecending order 
sorted_index = np.argsort(eigen_value)[::-1]

sorted_eigen_value = eigen_value[sorted_index]

#similiarly sorth the vector

sorted_eigen_vector = eigen_vector[:,sorted_index]

print("Sorted Value", sorted_eigen_value)
print("Sorted vector", sorted_eigen_vector )
    

Sorted Value [279.56681518 197.51579825 137.6545031   83.44288927  57.71473105]
Sorted vector [[-0.42327034  0.27870518  0.62337197 -0.41129707  0.43059001]
 [ 0.74805919  0.05282293  0.33432095  0.28839279  0.49262185]
 [-0.3977848  -0.64492624  0.29196731  0.56556942  0.14395734]
 [-0.32027454  0.58262088 -0.37110496  0.53901049  0.36017485]
 [ 0.02100332  0.40516196  0.52599724  0.37049053 -0.64920438]]


In [10]:
#select the first n eigenvectors , n is desired dimension  of our final reduced data
n_comp = 2
eigen_vector_subset= sorted_eigen_vector[:,0:n_comp]

In [14]:
#transform data 
x_reduced = np.dot(eigen_vector_subset.transpose(),x_mean.transpose()).transpose()

#visualize the shape
x_reduced.shape

(20, 2)

In [15]:
print(x_reduced)

[[ -6.80028391 -24.40387423]
 [ -1.77849165 -16.09511234]
 [ 33.56046876  -3.90414725]
 [-13.0221727    9.9289598 ]
 [ 18.88198553  -5.5761252 ]
 [ 15.03617728  14.95490778]
 [  7.39252293  21.42030284]
 [  8.52979283 -10.45754032]
 [-15.37500049  10.92488327]
 [ 11.07031721  -9.45766831]
 [-16.94471176 -26.56982119]
 [-24.80200277   9.57070414]
 [ 27.26891983   1.0652107 ]
 [  2.80520234  -4.37105606]
 [-11.37279172  -8.48803925]
 [ -8.73645383 -10.06342711]
 [-15.76839434   4.97881793]
 [ -0.68457528  18.36531798]
 [-23.94519713  15.19796192]
 [ 14.68468886  12.97974491]]
